lib/ring_logger.ex
The return value from init was in an extra tuple which wasn't what
:gen_event wanted.
=> Fix return value from init; add specs to verify

lib/ring_logger/client.ex, test/ring_logger_test.exs
Log messages are technically iodata, so they need to be flattened to
normal strings before sending them through Regex.match?/2.
=> Fix crash when grep'ing iodata

lib/ring_logger/client.ex, test/ring_logger/client_test.exs
I noticed that `RingLogger.Client.configure/2` only configured the `:io` and `:level` fields, so I was not able to configure other fields. I experienced this when I would attach and detach and then attach again with a different configuration. As reattaching tries to update the configuration if needed. This should allow all config fields to be configurable as advertised in the docs and type specs.
=> fix clients can not be fully configured at runtime

README.md, lib/ring_logger.ex, lib/ring_logger/client.ex, test/ring_logger_test.exs
I am opening this PR to start the conversation about getting module level filtering in for RingLogger. I would love feedback. Basically, this adds the ability to:
```
iex> RingLogger.attach(module_levels: %{SomeModule => :info})
```
To allow for `:info` and above logging to take place for this module. 
Also, it allows for filtering the whole project on a higher level, but a particular module, or a subset of modules, to log at a lower level like so:
```
iex> RingLogger.attach(module_levels: %{SomeModule => :debug}, level: :warn)
```
In the example above log messages at the `:debug` level will be logged, but every other module will be logging at the `:warn` level.
This PR does not support doing this at the `config.exs` file, but I can add that in this PR, or make another PR for that if that …
=> Provide module level filtering

README.md, lib/ring_logger.ex, lib/ring_logger/client.ex, test/ring_logger_test.exs
This lets you completely turn off logs from modules by specifying
`:none`.
=> Support filtering out all log messages using :none

lib/ring_logger/client.ex, test/ring_logger_test.exs
This fixes the GenServer timeouts when next, tail, and grep have a lot
to print over a slow connection. Now if anything goes wrong or takes
unexpectantly long, it will come from an IO.binwrite call in the
caller's context. This had two unintended benefits:
1. One call to IO.binwrite. Apparently I missed that I had iodata
before. This removes calls to Enum.each.
2. grep now grep's the entire log message instead of just the message
part. You can grep on timestamps and debug level now.
The downside to #1 is that it had an effect on the unit tests since all
output comes at once. I updated the unit tests to expect this.
=> Print in the context of the caller

lib/ring_logger.ex, lib/ring_logger/autoclient.ex, lib/ring_logger/client.ex, test/ring_logger_test.exs
This removes the hardcoded printout and allows users to pass a custom
pager.
=> Add option for specifying a pager

lib/ring_logger.ex, lib/ring_logger/autoclient.ex, lib/ring_logger/client.ex, test/ring_logger_test.exs
This also returns a nicer error if a Regex or String isn't passed.
=> Support strings being passed to grep

README.md, lib/ring_logger.ex, lib/ring_logger/client.ex, test/ring_logger/client_test.exs
Allows you to filter logging for an entire OTP app instead of specifying every module level for that app. (Very helpful for calming noisy apps)
This will ease @fhunleth sanity..
=> Support filtering at the application level

README.md, lib/ring_logger/client.ex
Adds ability to specify default RingLogger.Client options in `config.exs`
=> Support client options in configuration

lib/ring_logger/client.ex, test/ring_logger_test.exs
Before if no messages were printed, it could either be due to there not
being any messages or them all being filtered away. `RingLogger.next/1`
now prints summaries like the following:
```
iex> RingLogger.next
All 72 new messages filtered out.
```
```
iex> RingLogger.next
No new messages.
```
```
iex> RingLogger.next
...
1 out of 18 new messages shown.
```
=> Print summary at end of RingLogger.next/1

lib/ring_logger/circular_buffer.ex, lib/ring_logger/server.ex
This builds off in progress updates to the `circular_buffer` library to
optimize it for the circular buffer case. This update reduces the work
involved with storing log records. Currently other parts of RingLogger
dominate in timings so the improvement from this update can only be seen
if carefully monitoring the amount of memory used.
=> Switch to custom circular buffer implementation

.circleci/config.yml, lib/ring_logger/client.ex
- CI: Use OTP-24 built version of Elixir 1.12
- Fix OTP 24 Dialyzer warning
=> Erlang 24 fixes

.circleci/config.yml
CircleCI won't build PRs from forks and it looks like it is due to not
being able to pass secrets. No secrets are needed to built RingLogger,
so remove references to the org-global context.
=> CI: org-global isn't needed

README.md, lib/ring_logger/client.ex, test/ring_logger/client_test.exs, test/support/application_env_helpers.ex
Currently when `Logger.configure_backend` is called the configuration is stored under `:logger, RingLogger` but the initial configuration was still being read from `:ring_logger`
Also the `colors` configuration in the documentation had a typo
=> Allow full configuring under logger application

lib/ring_logger/client.ex, test/ring_logger_test.exs
Making the grep result stand out a bit can be really helpful at times (who doesn't like color?!)
Right now it will colorize all grep results if color is enabled. Should this be explicit with `grep_color: true | false`, or would this be an acceptable default?
=> Colorize grep results

lib/ring_logger/client.ex
The default for outputting color is determined by `IO.ANSI.enabled?`, but it
is applied in the `%RingLogger.Client.State{}` struct which is evaluated at
compile time so it will always be `false` and remove the color output.
This change forces in a `:colors` option key when building defaults if it
was not already present (which is normally the case). This will then cause
the config check to go through the configuring colors option which evaluates
`IO.ANSI.enabled?` at runtime for more accurate settings for the prints.
=> Fix setting colors enabled

lib/ring_logger.ex, lib/ring_logger/client.ex, test/ring_logger_test.exs
`:before` and `:after` options can be used with grep to include more
lines before/after the match. Helpful for cases where you might want to
see a little more data in series but don't know exact search terms.
Mimics `-A` and `-B` options of `grep`
=> Support `:before` and `:after` options in grep

.circleci/config.yml, lib/ring_logger.ex, mix.exs
* remove deprecated `:race_conditions` dialyzer option
* Add new `:missing_return` and `:extra_return` dialyzer options
* Update Elixir/Erlang CI versions
=> Support OTP 25

lib/ring_logger.ex, lib/ring_logger/client.ex
Unicode charlist crashes RingLogger. Logger's messages are `:unicode.chardata` not `iodata`.
```elixir
Logger.debug ~c"Cześć!"
```
=> Fix unicode chardata support

.circleci/config.yml, test/ring_logger/client_test.exs, test/ring_logger_test.exs, test/stress_test.exs
Elixir 1.4 removed support for `$levelpad` and dropped it from the
default formatter pattern. This updates the unit tests to force a format
pattern rather than relying on the default one.
=> Fix unit tests for Elixir 1.4

test/ring_logger_test.exs, test/stress_test.exs
This didn't affect the results of any tests since the inputs are limited
to ASCII characters.
=> Replace more incorrect uses of iodata_to_binary

README.md, benchmarks/buffers.exs, lib/ring_logger.ex, lib/ring_logger/buffer.ex, lib/ring_logger/server.ex, mix.exs, mix.lock, test/ring_logger_test.exs, test/stress_test.exs
If configured, allow for multiple buffers that are merged based on monotonic time. This allows for lower level logs to not be wiped out by verbose debug logging.
=> Allow for multiple circular buffers based on log level

lib/ring_logger.ex, lib/ring_logger/client.ex, lib/ring_logger/server.ex, test/ring_logger_test.exs
This lets us pick out the pieces we want instead of remembering the tuple position of everything. Memory is the same per benchee.
=> Store log entries as maps instead of tuples

README.md, lib/ring_logger.ex, lib/ring_logger/client.ex, lib/ring_logger/persistence.ex, lib/ring_logger/server.ex, test/ring_logger/persistence_test.exs, test/ring_logger_test.exs
Persist the current circular buffers every `:persist_seconds`. When the backend starts, try to load the persisted logs and reinsert into the configured buffers.
=> Periodically save the current buffers to a file, load on start

lib/ring_logger.ex
Noticed what seems to be a tiny typo while upgrading to 0.10.
=> Fix `entry` typespec typo

lib/ring_logger/client.ex
This is a public function by mistake, let's make it private.
=> fix(client): make has_metadata? private

lib/ring_logger/server.ex, test/ring_logger_test.exs
When starting the RingLogger backend, the `RingLogger.Server` loads any history from a persistence file during init, then configures the Server after successfully starting up. However, the configure action was destructive and would reset all the buffers which were just loaded if you happened to have buffer configuration.
This fixes that to reload any existing buffer back into the newly configured ones so that history would not be lost when adjusting minor configuration
=> Fix loading history when multiple buffers in config

lib/ring_logger/viewer.ex
This changes the log message to search for to the more common Linux
version string. The "Booting Linux on..." message isn't universally
printed. This also handles the message not being found.
=> Viewer: fix boot index failure

lib/ring_logger.ex, test/ring_logger_test.exs
This fixes an issue where ASCII data got passed through that was a
little corrupt and it triggered a crash. This bulletproofs the
flattening code against junk being logged.
=> Don't crash on non-Unicode data

lib/ring_logger/viewer.ex
Lessens the requirements for terminal width by reducing the min log line length to `25` (down from `30`)
=> Set the minimum log viewer line width to 25

lib/ring_logger/server.ex
If the logs are being persisted periodically, then it would also be useful if they are persisted as part of a terminate event to avoid losing logs to a `Nerves.Runtime.reboot/0`.
=> Persist logs on terminate if appropriate.
